[functions.send-push-notification]
verify_jwt = false

[functions.send-auction-email]
verify_jwt = false

[functions.finalize-auctions]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.public-batch-info]
verify_jwt = false

[functions.public-consumer-marketplace]
verify_jwt = false

[functions.consumer-order-action]
verify_jwt = false
